# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfsha.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dfsha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x66sha.proto\x12\x05\x64\x66sha\"9\n\x05\x42lock\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t\"\x1b\n\x07\x42lockId\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xaa\x01\n\x08\x44\x61taNode\x12&\n\nWriteBlock\x12\x0c.dfsha.Block\x1a\n.dfsha.Ack\x12)\n\tReadBlock\x12\x0e.dfsha.BlockId\x1a\x0c.dfsha.Block\x12)\n\x0b\x44\x65leteBlock\x12\x0e.dfsha.BlockId\x1a\n.dfsha.Ack\x12 \n\x04Ping\x12\x0c.dfsha.Empty\x1a\n.dfsha.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfsha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCK']._serialized_start=22
  _globals['_BLOCK']._serialized_end=79
  _globals['_BLOCKID']._serialized_start=81
  _globals['_BLOCKID']._serialized_end=108
  _globals['_ACK']._serialized_start=110
  _globals['_ACK']._serialized_end=149
  _globals['_EMPTY']._serialized_start=151
  _globals['_EMPTY']._serialized_end=158
  _globals['_DATANODE']._serialized_start=161
  _globals['_DATANODE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
