# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dfsha_pb2 as dfsha__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataNodeStub:
    """Servicio expuesto por cada DataNode.
    Cliente -> DataNode: WriteBlock / ReadBlock / DeleteBlock
    ControlNode -> DataNode: Ping (chequeo de salud, opcional)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteBlock = channel.unary_unary(
                '/dfsha.DataNode/WriteBlock',
                request_serializer=dfsha__pb2.Block.SerializeToString,
                response_deserializer=dfsha__pb2.Ack.FromString,
                _registered_method=True)
        self.ReadBlock = channel.unary_unary(
                '/dfsha.DataNode/ReadBlock',
                request_serializer=dfsha__pb2.BlockId.SerializeToString,
                response_deserializer=dfsha__pb2.Block.FromString,
                _registered_method=True)
        self.DeleteBlock = channel.unary_unary(
                '/dfsha.DataNode/DeleteBlock',
                request_serializer=dfsha__pb2.BlockId.SerializeToString,
                response_deserializer=dfsha__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/dfsha.DataNode/Ping',
                request_serializer=dfsha__pb2.Empty.SerializeToString,
                response_deserializer=dfsha__pb2.Ack.FromString,
                _registered_method=True)


class DataNodeServicer:
    """Servicio expuesto por cada DataNode.
    Cliente -> DataNode: WriteBlock / ReadBlock / DeleteBlock
    ControlNode -> DataNode: Ping (chequeo de salud, opcional)
    """

    def WriteBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteBlock,
                    request_deserializer=dfsha__pb2.Block.FromString,
                    response_serializer=dfsha__pb2.Ack.SerializeToString,
            ),
            'ReadBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlock,
                    request_deserializer=dfsha__pb2.BlockId.FromString,
                    response_serializer=dfsha__pb2.Block.SerializeToString,
            ),
            'DeleteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlock,
                    request_deserializer=dfsha__pb2.BlockId.FromString,
                    response_serializer=dfsha__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=dfsha__pb2.Empty.FromString,
                    response_serializer=dfsha__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.DataNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.DataNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataNode:
    """Servicio expuesto por cada DataNode.
    Cliente -> DataNode: WriteBlock / ReadBlock / DeleteBlock
    ControlNode -> DataNode: Ping (chequeo de salud, opcional)
    """

    @staticmethod
    def WriteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DataNode/WriteBlock',
            dfsha__pb2.Block.SerializeToString,
            dfsha__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DataNode/ReadBlock',
            dfsha__pb2.BlockId.SerializeToString,
            dfsha__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DataNode/DeleteBlock',
            dfsha__pb2.BlockId.SerializeToString,
            dfsha__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DataNode/Ping',
            dfsha__pb2.Empty.SerializeToString,
            dfsha__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
